import path from 'node:path';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { writeIndividualStockEvidence } from '../src/lib/individual-stock-evidence.js';
import { writeEvidenceQuality } from '../src/lib/evidence-quality.js';
import { writeAnalysisEvidencePack } from '../src/lib/analysis-evidence-pack.js';
import { writeAnalysisReadiness } from '../src/lib/analysis-readiness.js';
import type { ResearchManifest, SourceArtifact } from '../src/types/research.js';

const ROOT = process.cwd();
const TICKER = 'ITC';
const DIR = path.join(ROOT, 'research', TICKER);
const NOW = '2026-10-08T00:00:00.000Z';

async function json(rel:string, value:any) {
  const file = path.join(DIR, rel);
  await mkdir(path.dirname(file), { recursive:true });
  await writeFile(file, JSON.stringify(value, null, 2), 'utf8');
}
async function text(rel:string, value:string) {
  const file = path.join(DIR, rel);
  await mkdir(path.dirname(file), { recursive:true });
  await writeFile(file, value, 'utf8');
}
async function binary(rel:string) {
  const file = path.join(DIR, rel);
  await mkdir(path.dirname(file), { recursive:true });
  await writeFile(file, Buffer.from([0]));
}
function artifact(id:string, type:SourceArtifact['type'], provider:string, rel:string, status:SourceArtifact['status']='ok'):SourceArtifact {
  return { id, type, provider, title:'Fixture ' + id, localPath:path.join(DIR, rel), retrievedAt:NOW, status, method:'script',
    notes:['Generated by deterministic CI test fixture; not live provider data.'] };
}

async function main() {
  await rm(DIR, { recursive:true, force:true });
  await mkdir(path.join(DIR,'raw'), { recursive:true });
  await mkdir(path.join(DIR,'normalized'), { recursive:true });
  await mkdir(path.join(DIR,'markdown'), { recursive:true });
  await mkdir(path.join(DIR,'screenshots'), { recursive:true });

  const artifacts:SourceArtifact[] = [
    artifact('nse-api-symbol-data','market_data','NSE','raw/nse-api/quote-normalized.json'),
    artifact('nse-api-symbol-metadata','market_data','NSE','raw/nse-api/symbol-metadata-normalized.json'),
    artifact('nse-api-symbol-name','market_data','NSE','raw/nse-api/symbol-name-normalized.json'),
    artifact('nse-api-financial-results','financials','NSE','raw/nse-api/financial-results.json'),
    artifact('nse-nextapi-financial-status','financials','NSE','raw/nse-api/nextapi/financials/financial-status.json'),
    artifact('nse-nextapi-financial-result-data','financials','NSE','raw/nse-api/nextapi/financials/financial-result-data.json'),
    artifact('nse-api-corporate-announcements','source_page','NSE','raw/nse-api/corporate-announcements.json'),
    artifact('nse-nextapi-corporate-announcements','source_page','NSE','raw/nse-api/nextapi/corporate/corporate-announcements-nextapi.json'),
    artifact('nse-api-corporate-actions','source_page','NSE','raw/nse-api/corporate-actions.json'),
    artifact('nse-nextapi-corporate-actions','source_page','NSE','raw/nse-api/nextapi/corporate/corporate-actions-nextapi.json'),
    artifact('nse-nextapi-board-meetings','source_page','NSE','raw/nse-api/nextapi/corporate/board-meetings.json'),
    artifact('nse-nextapi-event-calendar','source_page','NSE','raw/nse-api/nextapi/corporate/event-calendar.json'),
    artifact('nse-nextapi-shareholding-pattern','shareholding','NSE','raw/nse-api/nextapi/ownership/shareholding-pattern-nextapi.json'),
    artifact('nse-api-yearwise','market_data','NSE','raw/nse-api/yearwise-normalized.json'),
    artifact('nse-api-symbol-chart-1d','market_data','NSE','raw/nse-api/symbol-chart-1d-normalized.json'),
    artifact('nse-nextapi-annual-reports-index','annual_report','NSE','raw/nse-api/nextapi/annual_reports/annual-reports-index.json'),
    artifact('nse-nextapi-peer-comparison','market_data','NSE','raw/nse-api/nextapi/peers/peer-comparison.json'),
    artifact('nse-annual-report-fixture','annual_report','NSE','raw/nse-api/annual-report-fixture.txt'),
    artifact('screener-fundamental-snapshot','screener_fundamentals','Screener','raw/screener/fundamental-snapshot.json'),
    artifact('tijori-financial-context','financials','Tijori','raw/tijori/financial-context.json'),
    artifact('tradingview-technical-normalized','technical_chart','TradingView','raw/tradingview/technical-normalized.json')
  ];

  await json('raw/nse-api/quote-normalized.json', {
    symbol:'ITC', lastPrice:450, previousClose:448, open:449, dayHigh:453, dayLow:447,
    averagePrice:450, pChange:0.45, volume:1000000, turnover:450000000,
    marketCap:560000, totalMarketCap:560000, sector:'FMCG', industry:'Tobacco'
  });
  await json('raw/nse-api/symbol-metadata-normalized.json', {
    activeSeries:'EQ', marketType:'N', parentSymbol:'ITC', isFNOSec:false, isSLBSec:false,
    isSuspended:false, isETFSec:false, isDelisted:false
  });
  await json('raw/nse-api/symbol-name-normalized.json', { companyName:'ITC Limited' });
  await json('raw/nse-api/financial-results.json', { resCmpData:[
    { period:'Mar 2026', revenue:180000, operatingProfit:42000, profitAfterTax:32000, eps:26, ebitda:44000 }
  ]});
  await json('raw/nse-api/nextapi/financials/financial-status.json', [
    { to_date_MonYr:'Mar 2026', totalIncome:'180000', expenditure:'138000', reProLossBefTax:'42000', netProLossAftTax:'32000', eps:'26' }
  ]);
  await json('raw/nse-api/nextapi/financials/financial-result-data.json', [
    { to_date_MonYr:'Jun 2026', totalIncome:'47000', expenditure:'35000', reProLossBefTax:'12000', netProLossAftTax:'9000', eps:'7.3' }
  ]);
  await json('raw/nse-api/corporate-announcements.json', [{ symbol:'ITC', an_dt:'2026-10-01', desc:'Quarterly results announced', attchmntText:'Fixture announcement' }]);
  await json('raw/nse-api/corporate-actions.json', [{ symbol:'ITC', exDate:'2026-07-01', subject:'Dividend' }]);
  await json('raw/nse-api/nextapi/corporate/corporate-announcements-nextapi.json', [{ symbol:'ITC', an_dt:'2026-10-01', desc:'Quarterly results announced', attchmntText:'Fixture announcement' }]);
  await json('raw/nse-api/nextapi/corporate/corporate-actions-nextapi.json', [{ symbol:'ITC', exDate:'2026-07-01', subject:'Dividend' }]);
  await json('raw/nse-api/nextapi/corporate/board-meetings.json', [{ symbol:'ITC', bm_date:'2026-11-01', bm_desc:'Board meeting' }]);
  await json('raw/nse-api/nextapi/corporate/event-calendar.json', [{ date:'2026-11-15', event:'Earnings' }]);
  await json('raw/nse-api/nextapi/ownership/shareholding-pattern-nextapi.json', [
    { asOf:'Jun 2026', promoterHolding:0, fiiHolding:41, diiHolding:43, publicHolding:16, promoterPledge:0 }
  ]);
  await json('raw/nse-api/yearwise-normalized.json', [{ period:'1Y', stockChangePct:8, indexChangePct:6 }]);
  await json('raw/nse-api/symbol-chart-1d-normalized.json', [{ time:'2026-10-07', close:450, volume:1000000 }]);
  await json('raw/nse-api/nextapi/annual_reports/annual-reports-index.json', [
    { companyName:'ITC Limited', fromYr:'2025', toYr:'2026', fileName:'itc-annual-report.pdf', broadcast_dttm:NOW }
  ]);
  await text('raw/nse-api/annual-report-fixture.txt','fixture annual report');
  await json('raw/nse-api/nextapi/peers/peer-comparison.json', [
    { symbol:'ITC', series:'EQ', marketCap:560000, ltp:450, eps:26, pe:17, promoterHolding:0, pChange:0.45 }
  ]);

  await json('raw/screener/fundamental-snapshot.json', {
    companyName:'ITC Limited',
    tables:[
      { caption:'Ratios', headers:['Metric','Value'], rows:[
        ['Market Cap','560000'], ['Stock P/E','17'], ['Price to Book','4'], ['Book Value','112'],
        ['Dividend Yield','3.0'], ['ROCE','32'], ['ROE','28'], ['Debt','0'], ['Sales Growth','8'], ['Profit Growth','12'], ['Current Price','450']
      ]},
      { caption:'Profit & Loss', headers:['Period','Value'], rows:[['Mar 2026','32000']]},
      { caption:'Balance Sheet', headers:['Period','Value'], rows:[['Mar 2026','100000']]},
      { caption:'Cash Flow', headers:['Period','Value'], rows:[['Mar 2026','25000']]},
      { caption:'Quarterly Results', headers:['Period','Value'], rows:[['Jun 2026','47000']]}
    ]
  });
  await json('raw/tijori/financial-context.json', {
    capturedAt:NOW,
    text:'Business context Revenue 180000 Profit 32000 Market Cap 560000 P/E 17 ROE 28 ROCE 32 Segment FMCG Ownership promoter public.'
  });
  await json('normalized/screener-financial-tables.json', {
    tables:[
      {caption:'Quarterly Results',headers:['Period','Revenue'],rows:[['Jun 2026','47000']]},
      {caption:'Profit & Loss',headers:['Period','PAT'],rows:[['Mar 2026','32000']]},
      {caption:'Balance Sheet',headers:['Period','Debt'],rows:[['Mar 2026','0']]},
      {caption:'Cash Flow',headers:['Period','Cash'],rows:[['Mar 2026','25000']]},
      {caption:'Ratios',headers:['Metric','Value'],rows:[['ROE','28']]}
    ]
  });
  await json('normalized/tijori-context.json', { text:'Revenue Profit segment ownership conference call ROE ROCE P/E business industry' });
  await json('raw/tradingview/technical-normalized.json', {
    latest:{ date:'2026-10-07', close:450, ema50:440, ema200:400, rsi14:61, volume:1000000 }
  });

  await json('raw/tradingview/symbol-scanner-normalized.json', { symbol:'ITC' });
  await json('raw/news-sentiment.json', { headlines:[] });

  for (const file of ['tradingview-1d.png','tradingview-fullchart-5y.png','tradingview-fullchart-all.png','tradingview-technicals.png']) await binary('screenshots/' + file);

  const manifest:ResearchManifest = {
    schema_version:'1.49', ticker:TICKER, companyName:'ITC Limited', isin:'INE154A01025', runId:'fixture-itc',
    input:{raw:'ITC',normalized:'ITC',exchange:'NSE',instrumentType:'equity'},
    features:{chartinkEnabled:false}, generatedAt:NOW, acquisitionOnly:true,
    sourceArtifacts:artifacts, dataGaps:[], warnings:[]
  };

  await json('manifest.json', manifest);
  await json('raw/nse-api/historical-validation.json', { coverageRatio:1 });
  await json('raw/nse-api/historical-quality.json', { qualityStatus:'ok' });

  await text('markdown/STRUCTURED_EVIDENCE.md','# Fixture structured evidence\\n');
  await text('markdown/ALL_EVIDENCE.md','# Fixture all evidence\\n');
  await text('markdown/MDA_EVIDENCE.md','# Fixture MDA\\n');
  await json('markdown/INGESTION_REPORT.json', { ok:true });
  await text('analysis-prompt.txt','Fixture analysis prompt');
  await json('evidence-contract.json', {
    schema_version:'1.0', summary:{factCount:12,calculatedMetricCount:4,sourceEvidenceCount:10},
    sections:{FACTS:[{field:'revenue',value:180000}],CALCULATED_METRICS:[{field:'ema50',value:440}],SOURCE_EVIDENCE:[{source:'NSE'}]}
  });
  await json('source-health.json', { overall:{status:'ok'}, sources:{} });
  await json('evidence-bundle.json', { deterministic:true,ticker:TICKER });
  await json('normalized/analysis-inputs.json', { deterministic:true,ticker:TICKER });

  await writeIndividualStockEvidence(DIR, manifest);
  const quality = await writeEvidenceQuality(DIR, manifest);
  await writeAnalysisEvidencePack(DIR, manifest);
  const readiness = await writeAnalysisReadiness(DIR, manifest);
  console.log(JSON.stringify({ok:true,ticker:TICKER,readiness:readiness.report.ready,quality:quality.report.status},null,2));
}
main().catch(error=>{console.error(error instanceof Error ? error.stack || error.message : String(error));process.exit(1);});
